:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore src\projectManagement.API
dotnet build src\projectManagement.API
echo Now, run the following to start the project: dotnet run -p src\projectManagement.API\projectManagement.API.csproj --launch-profile web.
echo.
